task('deploy:SJRouter')
  .addParam('yaho', 'Yaho address')
  .addParam('yaru', 'Yahu address')
  .addParam('factory', 'xERC20 Factory')
  .setAction(async (_args) => {
    const SJRouter = await ethers.getContractFactory('SJRouter')
    console.log('Deploying SJRouter ...')
    const sjRouter = await SJRouter.deploy(_args.yaho, _args.yahu, _args.factory)
    console.log('SJRouter deployed at:', sjRouter.address)
  })
